// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILy-1qDHRa6mZthxrp2IcD5mw_ORT7DY',
    appId: '1:937969185196:android:d697e639a317a819bf0a09',
    messagingSenderId: '937969185196',
    projectId: 'instagramclonef',
    databaseURL: 'https://instagramclonef-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclonef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbViDstwn8YuLNdXNBu6z5o4Pt23ZJhk',
    appId: '1:937969185196:ios:08659ec636f80eecbf0a09',
    messagingSenderId: '937969185196',
    projectId: 'instagramclonef',
    databaseURL: 'https://instagramclonef-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclonef.appspot.com',
    iosClientId: '937969185196-1shatmi7a73cjl59ng52ke7tk55c5s0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramDemoApp',
  );
}
